FROM php:7.4-apache-buster


# Inits the apps/ volume
COPY   apps/       ./apps
COPY   config-docker-php.json ./apps/config.json
RUN    chown -R www-data:www-data /var/www/html/apps

# Note: this is the admin's responsability to
# make sure the following directory will be write-readable
VOLUME [ "/var/www/html/apps" ]

# Copies the static resources
COPY css/        ./css
COPY img/        ./img
COPY index.html  ./index.html
COPY js/         ./js
COPY lib/        ./lib

# Copies the PHP backend
COPY srv/php ./srv

