services:
  # Python version
  # Served under /${MVIEWERSTUDIO_URL_PATH_PREFIX}/ see docker/nginx/default.conf.template
  mviewerstudio:
    build:
      context: .
      dockerfile: docker/Dockerfile
      network: host
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    pull_policy: build
    image: mviewer/mviewerstudio:qgis
    user: "${UID:-1000}:${GID:-1000}"
#    ports:
#      - "8000:8000"
    environment:
      - CONF_PATH_FROM_MVIEWER=apps/store
      - CONF_PUBLISH_PATH_FROM_MVIEWER=apps/public
      - DEFAULT_ORG=my_org
      - EXPORT_CONF_FOLDER=/home/mvuser/apps/store
      - MVIEWERSTUDIO_PUBLISH_PATH=/home/mvuser/apps/public
      - MVIEWERSTUDIO_URL_PATH_PREFIX=mviewerstudio
      - QGS_FOLDER=/home/mvuser/qgis
      - QGIS_SERVER_INTERNAL_URL=http://qgis-server/ogc/
    volumes:
      - "./apps:/home/mvuser/apps"
      - "./qgis:/home/mvuser/qgis"
      - "./src/static/config.json:/home/mvuser/src/static/config.json"
  # QGIS Server exposed on localhost:90 to match src/static/config.json
  qgis-server:
    profiles:
      - qgis
    image: qgis/qgis-server:latest
    ports:
      - "90:80"
    volumes:
      - "./qgis:/io/data"
  # Served under /mviewer/ see docker/nginx/default.conf.template
  mviewer:
    depends_on:
      - mviewerstudio
    # this image is automatically built in
    # the mviewer/mviewer github repository
    # See https://github.com/mviewer/mviewer/pull/236
    image: mviewer/mviewer
    # ports:
    #   - "5051:80"
    volumes:
        - "./apps:/usr/share/nginx/html/apps:ro"
  # Reverse-proxy using nginx. Groups mviewer and mviewerstudio under respective paths
  # Config can be found under ./docker/nginx/default.conf.template
  www:
    image: nginx
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - MVIEWERSTUDIO_URL_PATH_PREFIX=mviewerstudio
    volumes:
      - ./docker/nginx:/etc/nginx/templates
      - "./apps:/usr/share/nginx/html/apps:ro"
    depends_on:
      - mviewerstudio
      - mviewer
