FROM python:3.8-slim

RUN useradd -r -m apprunner

USER apprunner

ENV HOME=/home/apprunner
ENV PATH=$HOME/.local/bin:$PATH
ENV EXPORT_CONF_FOLDER=/home/apprunner/apps/store

RUN mkdir -p /home/apprunner/apps/store
RUN chown -R apprunner:apprunner /home/apprunner/apps

WORKDIR /home/apprunner

COPY srv/python/requirements.txt .
RUN pip install --user -r requirements.txt

COPY --chown=apprunner:apprunner srv/python .
RUN pip install --user . && pip install --user gunicorn

RUN rm -rf mviewerstudio_backend/static/*

VOLUME [ "/home/apprunner/apps" ]

COPY css/        mviewerstudio_backend/static/css
COPY img/        mviewerstudio_backend/static/img
COPY index.html  mviewerstudio_backend/static/index.html
COPY mviewerstudio.i18n.json mviewerstudio_backend/static/mviewerstudio.i18n.json
COPY js/         mviewerstudio_backend/static/js
COPY lib/        mviewerstudio_backend/static/lib
COPY *.json      mviewerstudio_backend/static/
COPY docker/config-docker-python.json mviewerstudio_backend/static/apps/config.json

CMD ["gunicorn", "-w 4", "-b 0.0.0.0:8000", "mviewerstudio_backend.app:app"]
