FROM python:3.11-slim

#install git & studio dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libxml2-dev \
        libxslt1-dev \
        git \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -r -m apprunner

USER apprunner

ENV HOME=/home/apprunner
ENV PATH=$HOME/.local/bin:$PATH

RUN mkdir -p /home/apprunner/apps/store
RUN chown -R apprunner:apprunner /home/apprunner/apps

WORKDIR /home/apprunner

COPY --chown=apprunner:apprunner srv/python .
# We need to install the app so that the config is properly read (there might be something to fix on
# app-factory.py, calling app.config.from_object requires the package to be installed
RUN pip install --user -r requirements.txt && pip install --user .

VOLUME [ "/home/apprunner/apps" ]

COPY css/        mviewerstudio_backend/static/css
COPY img/        mviewerstudio_backend/static/img
COPY index.html  mviewerstudio_backend/static/index.html
COPY js/         mviewerstudio_backend/static/js
COPY lib/        mviewerstudio_backend/static/lib
COPY mviewerstudio.i18n.json      mviewerstudio_backend/static/mviewerstudio.i18n.json

ENV EXPORT_CONF_FOLDER=/home/apprunner/apps/store \
    CONF_PATH_FROM_MVIEWER=apps/store \
    MVIEWERSTUDIO_PUBLISH_PATH=/home/apprunner/apps/public \
    CONF_PUBLISH_PATH_FROM_MVIEWER=apps/public \
    DEFAULT_ORG=public \
    MVIEWERSTUDIO_URL_PATH_PREFIX=mviewerstudio/

# You will probably have to override this one on runtime with your custom config
COPY config-python-sample.json mviewerstudio_backend/static/apps/config.json

CMD ["gunicorn", "-w 4", "-b 0.0.0.0:8000", "mviewerstudio_backend.app:app"]
