var icons = [
{ icon: 'fab fa-500px' },
{ icon: 'fab fa-accessible-icon' },
{ icon: 'fab fa-accusoft' },
{ icon: 'fas fa-address-book' }, { icon: 'far fa-address-book' },
{ icon: 'fas fa-address-card' }, { icon: 'far fa-address-card' },
{ icon: 'fas fa-adjust' },
{ icon: 'fab fa-adn' },
{ icon: 'fab fa-adversal' },
{ icon: 'fab fa-affiliatetheme' },
{ icon: 'fab fa-algolia' },
{ icon: 'fas fa-align-center' },
{ icon: 'fas fa-align-justify' },
{ icon: 'fas fa-align-left' },
{ icon: 'fas fa-align-right' },
{ icon: 'fab fa-amazon' },
{ icon: 'fas fa-ambulance' },
{ icon: 'fas fa-american-sign-language-interpreting' },
{ icon: 'fab fa-amilia' },
{ icon: 'fas fa-anchor' },
{ icon: 'fab fa-android' },
{ icon: 'fab fa-angellist' },
{ icon: 'fas fa-angle-double-down' },
{ icon: 'fas fa-angle-double-left' },
{ icon: 'fas fa-angle-double-right' },
{ icon: 'fas fa-angle-double-up' },
{ icon: 'fas fa-angle-down' },
{ icon: 'fas fa-angle-left' },
{ icon: 'fas fa-angle-right' },
{ icon: 'fas fa-angle-up' },
{ icon: 'fab fa-angrycreative' },
{ icon: 'fab fa-angular' },
{ icon: 'fab fa-app-store' },
{ icon: 'fab fa-app-store-ios' },
{ icon: 'fab fa-apper' },
{ icon: 'fab fa-apple' },
{ icon: 'fab fa-apple-pay' },
{ icon: 'fas fa-archive' },
{ icon: 'fas fa-arrow-alt-circle-down' }, { icon: 'far fa-arrow-alt-circle-down' },
{ icon: 'fas fa-arrow-alt-circle-left' }, { icon: 'far fa-arrow-alt-circle-left' },
{ icon: 'fas fa-arrow-alt-circle-right' }, { icon: 'far fa-arrow-alt-circle-right' },
{ icon: 'fas fa-arrow-alt-circle-up' }, { icon: 'far fa-arrow-alt-circle-up' },
{ icon: 'fas fa-arrow-circle-down' },
{ icon: 'fas fa-arrow-circle-left' },
{ icon: 'fas fa-arrow-circle-right' },
{ icon: 'fas fa-arrow-circle-up' },
{ icon: 'fas fa-arrow-down' },
{ icon: 'fas fa-arrow-left' },
{ icon: 'fas fa-arrow-right' },
{ icon: 'fas fa-arrow-up' },
{ icon: 'fas fa-arrows-alt' },
{ icon: 'fas fa-arrows-alt-h' },
{ icon: 'fas fa-arrows-alt-v' },
{ icon: 'fas fa-assistive-listening-systems' },
{ icon: 'fas fa-asterisk' },
{ icon: 'fab fa-asymmetrik' },
{ icon: 'fas fa-at' },
{ icon: 'fab fa-audible' },
{ icon: 'fas fa-audio-description' },
{ icon: 'fab fa-autoprefixer' },
{ icon: 'fab fa-avianex' },
{ icon: 'fab fa-aviato' },
{ icon: 'fab fa-aws' },
{ icon: 'fas fa-backward' },
{ icon: 'fas fa-balance-scale' },
{ icon: 'fas fa-ban' },
{ icon: 'fab fa-bandcamp' },
{ icon: 'fas fa-barcode' },
{ icon: 'fas fa-bars' },
{ icon: 'fas fa-bath' },
{ icon: 'fas fa-battery-empty' },
{ icon: 'fas fa-battery-full' },
{ icon: 'fas fa-battery-half' },
{ icon: 'fas fa-battery-quarter' },
{ icon: 'fas fa-battery-three-quarters' },
{ icon: 'fas fa-bed' },
{ icon: 'fas fa-beer' },
{ icon: 'fab fa-behance' },
{ icon: 'fab fa-behance-square' },
{ icon: 'fas fa-bell' }, { icon: 'far fa-bell' },
{ icon: 'fas fa-bell-slash' }, { icon: 'far fa-bell-slash' },
{ icon: 'fas fa-bicycle' },
{ icon: 'fab fa-bimobject' },
{ icon: 'fas fa-binoculars' },
{ icon: 'fas fa-birthday-cake' },
{ icon: 'fab fa-bitbucket' },
{ icon: 'fab fa-bitcoin' },
{ icon: 'fab fa-bity' },
{ icon: 'fab fa-black-tie' },
{ icon: 'fab fa-blackberry' },
{ icon: 'fas fa-blind' },
{ icon: 'fab fa-blogger' },
{ icon: 'fab fa-blogger-b' },
{ icon: 'fab fa-bluetooth' },
{ icon: 'fab fa-bluetooth-b' },
{ icon: 'fas fa-bold' },
{ icon: 'fas fa-bolt' },
{ icon: 'fas fa-bomb' },
{ icon: 'fas fa-book' },
{ icon: 'fas fa-bookmark' }, { icon: 'far fa-bookmark' },
{ icon: 'fas fa-braille' },
{ icon: 'fas fa-briefcase' },
{ icon: 'fab fa-btc' },
{ icon: 'fas fa-bug' },
{ icon: 'fas fa-building' }, { icon: 'far fa-building' },
{ icon: 'fas fa-bullhorn' },
{ icon: 'fas fa-bullseye' },
{ icon: 'fab fa-buromobelexperte' },
{ icon: 'fas fa-bus' },
{ icon: 'fab fa-buysellads' },
{ icon: 'fas fa-calculator' },
{ icon: 'fas fa-calendar' }, { icon: 'far fa-calendar' },
{ icon: 'fas fa-calendar-alt' }, { icon: 'far fa-calendar-alt' },
{ icon: 'fas fa-calendar-check' }, { icon: 'far fa-calendar-check' },
{ icon: 'fas fa-calendar-minus' }, { icon: 'far fa-calendar-minus' },
{ icon: 'fas fa-calendar-plus' }, { icon: 'far fa-calendar-plus' },
{ icon: 'fas fa-calendar-times' }, { icon: 'far fa-calendar-times' },
{ icon: 'fas fa-camera' },
{ icon: 'fas fa-camera-retro' },
{ icon: 'fas fa-car' },
{ icon: 'fas fa-caret-down' },
{ icon: 'fas fa-caret-left' },
{ icon: 'fas fa-caret-right' },
{ icon: 'fas fa-caret-square-down' }, { icon: 'far fa-caret-square-down' },
{ icon: 'fas fa-caret-square-left' }, { icon: 'far fa-caret-square-left' },
{ icon: 'fas fa-caret-square-right' }, { icon: 'far fa-caret-square-right' },
{ icon: 'fas fa-caret-square-up' }, { icon: 'far fa-caret-square-up' },
{ icon: 'fas fa-caret-up' },
{ icon: 'fas fa-cart-arrow-down' },
{ icon: 'fas fa-cart-plus' },
{ icon: 'fab fa-cc-amex' },
{ icon: 'fab fa-cc-apple-pay' },
{ icon: 'fab fa-cc-diners-club' },
{ icon: 'fab fa-cc-discover' },
{ icon: 'fab fa-cc-jcb' },
{ icon: 'fab fa-cc-mastercard' },
{ icon: 'fab fa-cc-paypal' },
{ icon: 'fab fa-cc-stripe' },
{ icon: 'fab fa-cc-visa' },
{ icon: 'fab fa-centercode' },
{ icon: 'fas fa-certificate' },
{ icon: 'fas fa-chart-area' },
{ icon: 'fas fa-chart-bar' }, { icon: 'far fa-chart-bar' },
{ icon: 'fas fa-chart-line' },
{ icon: 'fas fa-chart-pie' },
{ icon: 'fas fa-check' },
{ icon: 'fas fa-check-circle' }, { icon: 'far fa-check-circle' },
{ icon: 'fas fa-check-square' }, { icon: 'far fa-check-square' },
{ icon: 'fas fa-chevron-circle-down' },
{ icon: 'fas fa-chevron-circle-left' },
{ icon: 'fas fa-chevron-circle-right' },
{ icon: 'fas fa-chevron-circle-up' },
{ icon: 'fas fa-chevron-down' },
{ icon: 'fas fa-chevron-left' },
{ icon: 'fas fa-chevron-right' },
{ icon: 'fas fa-chevron-up' },
{ icon: 'fas fa-child' },
{ icon: 'fab fa-chrome' },
{ icon: 'fas fa-circle' }, { icon: 'far fa-circle' },
{ icon: 'fas fa-circle-notch' },
{ icon: 'fas fa-clipboard' }, { icon: 'far fa-clipboard' },
{ icon: 'fas fa-clock' }, { icon: 'far fa-clock' },
{ icon: 'fas fa-clone' }, { icon: 'far fa-clone' },
{ icon: 'fas fa-closed-captioning' }, { icon: 'far fa-closed-captioning' },
{ icon: 'fas fa-cloud' },
{ icon: 'fas fa-cloud-download-alt' },
{ icon: 'fas fa-cloud-upload-alt' },
{ icon: 'fab fa-cloudscale' },
{ icon: 'fab fa-cloudsmith' },
{ icon: 'fab fa-cloudversify' },
{ icon: 'fas fa-code' },
{ icon: 'fas fa-code-branch' },
{ icon: 'fab fa-codepen' },
{ icon: 'fab fa-codiepie' },
{ icon: 'fas fa-coffee' },
{ icon: 'fas fa-cog' },
{ icon: 'fas fa-cogs' },
{ icon: 'fas fa-columns' },
{ icon: 'fas fa-comment' }, { icon: 'far fa-comment' },
{ icon: 'fas fa-comment-alt' }, { icon: 'far fa-comment-alt' },
{ icon: 'fas fa-comments' }, { icon: 'far fa-comments' },
{ icon: 'fas fa-compass' }, { icon: 'far fa-compass' },
{ icon: 'fas fa-compress' },
{ icon: 'fab fa-connectdevelop' },
{ icon: 'fab fa-contao' },
{ icon: 'fas fa-copy' }, { icon: 'far fa-copy' },
{ icon: 'fas fa-copyright' }, { icon: 'far fa-copyright' },
{ icon: 'fab fa-cpanel' },
{ icon: 'fab fa-creative-commons' },
{ icon: 'fas fa-credit-card' }, { icon: 'far fa-credit-card' },
{ icon: 'fas fa-crop' },
{ icon: 'fas fa-crosshairs' },
{ icon: 'fab fa-css3' },
{ icon: 'fab fa-css3-alt' },
{ icon: 'fas fa-cube' },
{ icon: 'fas fa-cubes' },
{ icon: 'fas fa-cut' },
{ icon: 'fab fa-cuttlefish' },
{ icon: 'fab fa-d-and-d' },
{ icon: 'fab fa-dashcube' },
{ icon: 'fas fa-database' },
{ icon: 'fas fa-deaf' },
{ icon: 'fab fa-delicious' },
{ icon: 'fab fa-deploydog' },
{ icon: 'fab fa-deskpro' },
{ icon: 'fas fa-desktop' },
{ icon: 'fab fa-deviantart' },
{ icon: 'fab fa-digg' },
{ icon: 'fab fa-digital-ocean' },
{ icon: 'fab fa-discord' },
{ icon: 'fab fa-discourse' },
{ icon: 'fab fa-dochub' },
{ icon: 'fab fa-docker' },
{ icon: 'fas fa-dollar-sign' },
{ icon: 'fas fa-dot-circle' }, { icon: 'far fa-dot-circle' },
{ icon: 'fas fa-download' },
{ icon: 'fab fa-draft2digital' },
{ icon: 'fab fa-dribbble' },
{ icon: 'fab fa-dribbble-square' },
{ icon: 'fab fa-dropbox' },
{ icon: 'fab fa-drupal' },
{ icon: 'fab fa-dyalog' },
{ icon: 'fab fa-earlybirds' },
{ icon: 'fab fa-edge' },
{ icon: 'fas fa-edit' }, { icon: 'far fa-edit' },
{ icon: 'fas fa-eject' },
{ icon: 'fas fa-ellipsis-h' },
{ icon: 'fas fa-ellipsis-v' },
{ icon: 'fab fa-ember' },
{ icon: 'fab fa-empire' },
{ icon: 'fas fa-envelope' }, { icon: 'far fa-envelope' },
{ icon: 'fas fa-envelope-open' }, { icon: 'far fa-envelope-open' },
{ icon: 'fas fa-envelope-square' },
{ icon: 'fab fa-envira' },
{ icon: 'fas fa-eraser' },
{ icon: 'fab fa-erlang' },
{ icon: 'fab fa-etsy' },
{ icon: 'fas fa-euro-sign' },
{ icon: 'fas fa-exchange-alt' },
{ icon: 'fas fa-exclamation' },
{ icon: 'fas fa-exclamation-circle' },
{ icon: 'fas fa-exclamation-triangle' },
{ icon: 'fas fa-expand' },
{ icon: 'fas fa-expand-arrows-alt' },
{ icon: 'fab fa-expeditedssl' },
{ icon: 'fas fa-external-link-alt' },
{ icon: 'fas fa-external-link-square-alt' },
{ icon: 'fas fa-eye' },
{ icon: 'fas fa-eye-dropper' },
{ icon: 'fas fa-eye-slash' }, { icon: 'far fa-eye-slash' },
{ icon: 'fab fa-facebook' },
{ icon: 'fab fa-facebook-f' },
{ icon: 'fab fa-facebook-messenger' },
{ icon: 'fab fa-facebook-square' },
{ icon: 'fas fa-fast-backward' },
{ icon: 'fas fa-fast-forward' },
{ icon: 'fas fa-fax' },
{ icon: 'fas fa-female' },
{ icon: 'fas fa-fighter-jet' },
{ icon: 'fas fa-file' }, { icon: 'far fa-file' },
{ icon: 'fas fa-file-alt' }, { icon: 'far fa-file-alt' },
{ icon: 'fas fa-file-archive' }, { icon: 'far fa-file-archive' },
{ icon: 'fas fa-file-audio' }, { icon: 'far fa-file-audio' },
{ icon: 'fas fa-file-code' }, { icon: 'far fa-file-code' },
{ icon: 'fas fa-file-excel' }, { icon: 'far fa-file-excel' },
{ icon: 'fas fa-file-image' }, { icon: 'far fa-file-image' },
{ icon: 'fas fa-file-pdf' }, { icon: 'far fa-file-pdf' },
{ icon: 'fas fa-file-powerpoint' }, { icon: 'far fa-file-powerpoint' },
{ icon: 'fas fa-file-video' }, { icon: 'far fa-file-video' },
{ icon: 'fas fa-file-word' }, { icon: 'far fa-file-word' },
{ icon: 'fas fa-film' },
{ icon: 'fas fa-filter' },
{ icon: 'fas fa-fire' },
{ icon: 'fas fa-fire-extinguisher' },
{ icon: 'fab fa-firefox' },
{ icon: 'fab fa-first-order' },
{ icon: 'fab fa-firstdraft' },
{ icon: 'fas fa-flag' }, { icon: 'far fa-flag' },
{ icon: 'fas fa-flag-checkered' },
{ icon: 'fas fa-flask' },
{ icon: 'fab fa-flickr' },
{ icon: 'fab fa-fly' },
{ icon: 'fas fa-folder' }, { icon: 'far fa-folder' },
{ icon: 'fas fa-folder-open' }, { icon: 'far fa-folder-open' },
{ icon: 'fas fa-font' },
{ icon: 'fab fa-font-awesome' },
{ icon: 'fab fa-font-awesome-alt' },
{ icon: 'fab fa-font-awesome-flag' },
{ icon: 'fab fa-fonticons' },
{ icon: 'fab fa-fonticons-fi' },
{ icon: 'fab fa-fort-awesome' },
{ icon: 'fab fa-fort-awesome-alt' },
{ icon: 'fab fa-forumbee' },
{ icon: 'fas fa-forward' },
{ icon: 'fab fa-foursquare' },
{ icon: 'fab fa-free-code-camp' },
{ icon: 'fab fa-freebsd' },
{ icon: 'fas fa-frown' }, { icon: 'far fa-frown' },
{ icon: 'fas fa-futbol' }, { icon: 'far fa-futbol' },
{ icon: 'fas fa-gamepad' },
{ icon: 'fas fa-gavel' },
{ icon: 'fas fa-gem' }, { icon: 'far fa-gem' },
{ icon: 'fas fa-genderless' },
{ icon: 'fab fa-get-pocket' },
{ icon: 'fab fa-gg' },
{ icon: 'fab fa-gg-circle' },
{ icon: 'fas fa-gift' },
{ icon: 'fab fa-git' },
{ icon: 'fab fa-git-square' },
{ icon: 'fab fa-github' },
{ icon: 'fab fa-github-alt' },
{ icon: 'fab fa-github-square' },
{ icon: 'fab fa-gitkraken' },
{ icon: 'fab fa-gitlab' },
{ icon: 'fab fa-gitter' },
{ icon: 'fas fa-glass-martini' },
{ icon: 'fab fa-glide' },
{ icon: 'fab fa-glide-g' },
{ icon: 'fas fa-globe' },
{ icon: 'fab fa-gofore' },
{ icon: 'fab fa-goodreads' },
{ icon: 'fab fa-goodreads-g' },
{ icon: 'fab fa-google' },
{ icon: 'fab fa-google-drive' },
{ icon: 'fab fa-google-play' },
{ icon: 'fab fa-google-plus' },
{ icon: 'fab fa-google-plus-g' },
{ icon: 'fab fa-google-plus-square' },
{ icon: 'fab fa-google-wallet' },
{ icon: 'fas fa-graduation-cap' },
{ icon: 'fab fa-gratipay' },
{ icon: 'fab fa-grav' },
{ icon: 'fab fa-gripfire' },
{ icon: 'fab fa-grunt' },
{ icon: 'fab fa-gulp' },
{ icon: 'fas fa-h-square' },
{ icon: 'fab fa-hacker-news' },
{ icon: 'fab fa-hacker-news-square' },
{ icon: 'fas fa-hand-lizard' }, { icon: 'far fa-hand-lizard' },
{ icon: 'fas fa-hand-paper' }, { icon: 'far fa-hand-paper' },
{ icon: 'fas fa-hand-peace' }, { icon: 'far fa-hand-peace' },
{ icon: 'fas fa-hand-point-down' }, { icon: 'far fa-hand-point-down' },
{ icon: 'fas fa-hand-point-left' }, { icon: 'far fa-hand-point-left' },
{ icon: 'fas fa-hand-point-right' }, { icon: 'far fa-hand-point-right' },
{ icon: 'fas fa-hand-point-up' }, { icon: 'far fa-hand-point-up' },
{ icon: 'fas fa-hand-pointer' }, { icon: 'far fa-hand-pointer' },
{ icon: 'fas fa-hand-rock' }, { icon: 'far fa-hand-rock' },
{ icon: 'fas fa-hand-scissors' }, { icon: 'far fa-hand-scissors' },
{ icon: 'fas fa-hand-spock' }, { icon: 'far fa-hand-spock' },
{ icon: 'fas fa-handshake' }, { icon: 'far fa-handshake' },
{ icon: 'fas fa-hashtag' },
{ icon: 'fas fa-hdd' }, { icon: 'far fa-hdd' },
{ icon: 'fas fa-heading' },
{ icon: 'fas fa-headphones' },
{ icon: 'fas fa-heart' }, { icon: 'far fa-heart' },
{ icon: 'fas fa-heartbeat' },
{ icon: 'fab fa-hire-a-helper' },
{ icon: 'fas fa-history' },
{ icon: 'fas fa-home' },
{ icon: 'fab fa-hooli' },
{ icon: 'fas fa-hospital' }, { icon: 'far fa-hospital' },
{ icon: 'fab fa-hotjar' },
{ icon: 'fas fa-hourglass' }, { icon: 'far fa-hourglass' },
{ icon: 'fas fa-hourglass-end' },
{ icon: 'fas fa-hourglass-half' },
{ icon: 'fas fa-hourglass-start' },
{ icon: 'fab fa-houzz' },
{ icon: 'fab fa-html5' },
{ icon: 'fab fa-hubspot' },
{ icon: 'fas fa-i-cursor' },
{ icon: 'fas fa-id-badge' }, { icon: 'far fa-id-badge' },
{ icon: 'fas fa-id-card' }, { icon: 'far fa-id-card' },
{ icon: 'fas fa-image' }, { icon: 'far fa-image' },
{ icon: 'fas fa-images' }, { icon: 'far fa-images' },
{ icon: 'fab fa-imdb' },
{ icon: 'fas fa-inbox' },
{ icon: 'fas fa-indent' },
{ icon: 'fas fa-industry' },
{ icon: 'fas fa-info' },
{ icon: 'fas fa-info-circle' },
{ icon: 'fab fa-instagram' },
{ icon: 'fab fa-internet-explorer' },
{ icon: 'fab fa-ioxhost' },
{ icon: 'fas fa-italic' },
{ icon: 'fab fa-itunes' },
{ icon: 'fab fa-itunes-note' },
{ icon: 'fab fa-jenkins' },
{ icon: 'fab fa-joget' },
{ icon: 'fab fa-joomla' },
{ icon: 'fab fa-js' },
{ icon: 'fab fa-js-square' },
{ icon: 'fab fa-jsfiddle' },
{ icon: 'fas fa-key' },
{ icon: 'fas fa-keyboard' }, { icon: 'far fa-keyboard' },
{ icon: 'fab fa-keycdn' },
{ icon: 'fab fa-kickstarter' },
{ icon: 'fab fa-kickstarter-k' },
{ icon: 'fas fa-language' },
{ icon: 'fas fa-laptop' },
{ icon: 'fab fa-laravel' },
{ icon: 'fab fa-lastfm' },
{ icon: 'fab fa-lastfm-square' },
{ icon: 'fas fa-leaf' },
{ icon: 'fab fa-leanpub' },
{ icon: 'fas fa-lemon' }, { icon: 'far fa-lemon' },
{ icon: 'fab fa-less' },
{ icon: 'fas fa-level-down-alt' },
{ icon: 'fas fa-level-up-alt' },
{ icon: 'fas fa-life-ring' }, { icon: 'far fa-life-ring' },
{ icon: 'fas fa-lightbulb' }, { icon: 'far fa-lightbulb' },
{ icon: 'fab fa-line' },
{ icon: 'fas fa-link' },
{ icon: 'fab fa-linkedin' },
{ icon: 'fab fa-linkedin-in' },
{ icon: 'fab fa-linode' },
{ icon: 'fab fa-linux' },
{ icon: 'fas fa-lira-sign' },
{ icon: 'fas fa-list' },
{ icon: 'fas fa-list-alt' }, { icon: 'far fa-list-alt' },
{ icon: 'fas fa-list-ol' },
{ icon: 'fas fa-list-ul' },
{ icon: 'fas fa-location-arrow' },
{ icon: 'fas fa-lock' },
{ icon: 'fas fa-lock-open' },
{ icon: 'fas fa-long-arrow-alt-down' },
{ icon: 'fas fa-long-arrow-alt-left' },
{ icon: 'fas fa-long-arrow-alt-right' },
{ icon: 'fas fa-long-arrow-alt-up' },
{ icon: 'fas fa-low-vision' },
{ icon: 'fab fa-lyft' },
{ icon: 'fab fa-magento' },
{ icon: 'fas fa-magic' },
{ icon: 'fas fa-magnet' },
{ icon: 'fas fa-male' },
{ icon: 'fas fa-map' }, { icon: 'far fa-map' },
{ icon: 'fas fa-map-marker' },
{ icon: 'fas fa-map-marker-alt' },
{ icon: 'fas fa-map-pin' },
{ icon: 'fas fa-map-signs' },
{ icon: 'fas fa-mars' },
{ icon: 'fas fa-mars-double' },
{ icon: 'fas fa-mars-stroke' },
{ icon: 'fas fa-mars-stroke-h' },
{ icon: 'fas fa-mars-stroke-v' },
{ icon: 'fab fa-maxcdn' },
{ icon: 'fab fa-medapps' },
{ icon: 'fab fa-medium' },
{ icon: 'fab fa-medium-m' },
{ icon: 'fas fa-medkit' },
{ icon: 'fab fa-medrt' },
{ icon: 'fab fa-meetup' },
{ icon: 'fas fa-meh' }, { icon: 'far fa-meh' },
{ icon: 'fas fa-mercury' },
{ icon: 'fas fa-microchip' },
{ icon: 'fas fa-microphone' },
{ icon: 'fas fa-microphone-slash' },
{ icon: 'fab fa-microsoft' },
{ icon: 'fas fa-minus' },
{ icon: 'fas fa-minus-circle' },
{ icon: 'fas fa-minus-square' }, { icon: 'far fa-minus-square' },
{ icon: 'fab fa-mix' },
{ icon: 'fab fa-mixcloud' },
{ icon: 'fab fa-mizuni' },
{ icon: 'fas fa-mobile' },
{ icon: 'fas fa-mobile-alt' },
{ icon: 'fab fa-modx' },
{ icon: 'fab fa-monero' },
{ icon: 'fas fa-money-bill-alt' }, { icon: 'far fa-money-bill-alt' },
{ icon: 'fas fa-moon' }, { icon: 'far fa-moon' },
{ icon: 'fas fa-motorcycle' },
{ icon: 'fas fa-mouse-pointer' },
{ icon: 'fas fa-music' },
{ icon: 'fab fa-napster' },
{ icon: 'fas fa-neuter' },
{ icon: 'fas fa-newspaper' }, { icon: 'far fa-newspaper' },
{ icon: 'fab fa-nintendo-switch' },
{ icon: 'fab fa-node' },
{ icon: 'fab fa-node-js' },
{ icon: 'fab fa-npm' },
{ icon: 'fab fa-ns8' },
{ icon: 'fab fa-nutritionix' },
{ icon: 'fas fa-object-group' }, { icon: 'far fa-object-group' },
{ icon: 'fas fa-object-ungroup' }, { icon: 'far fa-object-ungroup' },
{ icon: 'fab fa-odnoklassniki' },
{ icon: 'fab fa-odnoklassniki-square' },
{ icon: 'fab fa-opencart' },
{ icon: 'fab fa-openid' },
{ icon: 'fab fa-opera' },
{ icon: 'fab fa-optin-monster' },
{ icon: 'fab fa-osi' },
{ icon: 'fas fa-outdent' },
{ icon: 'fab fa-page4' },
{ icon: 'fab fa-pagelines' },
{ icon: 'fas fa-paint-brush' },
{ icon: 'fab fa-palfed' },
{ icon: 'fas fa-paper-plane' }, { icon: 'far fa-paper-plane' },
{ icon: 'fas fa-paperclip' },
{ icon: 'fas fa-paragraph' },
{ icon: 'fas fa-paste' },
{ icon: 'fab fa-patreon' },
{ icon: 'fas fa-pause' },
{ icon: 'fas fa-pause-circle' }, { icon: 'far fa-pause-circle' },
{ icon: 'fas fa-paw' },
{ icon: 'fab fa-paypal' },
{ icon: 'fas fa-pen-square' },
{ icon: 'fas fa-pencil-alt' },
{ icon: 'fas fa-percent' },
{ icon: 'fab fa-periscope' },
{ icon: 'fab fa-phabricator' },
{ icon: 'fab fa-phoenix-framework' },
{ icon: 'fas fa-phone' },
{ icon: 'fas fa-phone-square' },
{ icon: 'fas fa-phone-volume' },
{ icon: 'fab fa-pied-piper' },
{ icon: 'fab fa-pied-piper-alt' },
{ icon: 'fab fa-pied-piper-pp' },
{ icon: 'fab fa-pinterest' },
{ icon: 'fab fa-pinterest-p' },
{ icon: 'fab fa-pinterest-square' },
{ icon: 'fas fa-plane' },
{ icon: 'fas fa-play' },
{ icon: 'fas fa-play-circle' }, { icon: 'far fa-play-circle' },
{ icon: 'fab fa-playstation' },
{ icon: 'fas fa-plug' },
{ icon: 'fas fa-plus' },
{ icon: 'fas fa-plus-circle' },
{ icon: 'fas fa-plus-square' }, { icon: 'far fa-plus-square' },
{ icon: 'fas fa-podcast' },
{ icon: 'fas fa-pound-sign' },
{ icon: 'fas fa-power-off' },
{ icon: 'fas fa-print' },
{ icon: 'fab fa-product-hunt' },
{ icon: 'fab fa-pushed' },
{ icon: 'fas fa-puzzle-piece' },
{ icon: 'fab fa-python' },
{ icon: 'fab fa-qq' },
{ icon: 'fas fa-qrcode' },
{ icon: 'fas fa-question' },
{ icon: 'fas fa-question-circle' }, { icon: 'far fa-question-circle' },
{ icon: 'fab fa-quora' },
{ icon: 'fas fa-quote-left' },
{ icon: 'fas fa-quote-right' },
{ icon: 'fas fa-random' },
{ icon: 'fab fa-ravelry' },
{ icon: 'fab fa-react' },
{ icon: 'fab fa-rebel' },
{ icon: 'fas fa-recycle' },
{ icon: 'fab fa-red-river' },
{ icon: 'fab fa-reddit' },
{ icon: 'fab fa-reddit-alien' },
{ icon: 'fab fa-reddit-square' },
{ icon: 'fas fa-redo' },
{ icon: 'fas fa-redo-alt' },
{ icon: 'fas fa-registered' }, { icon: 'far fa-registered' },
{ icon: 'fab fa-rendact' },
{ icon: 'fab fa-renren' },
{ icon: 'fas fa-reply' },
{ icon: 'fas fa-reply-all' },
{ icon: 'fab fa-replyd' },
{ icon: 'fab fa-resolving' },
{ icon: 'fas fa-retweet' },
{ icon: 'fas fa-road' },
{ icon: 'fas fa-rocket' },
{ icon: 'fab fa-rocketchat' },
{ icon: 'fab fa-rockrms' },
{ icon: 'fas fa-rss' },
{ icon: 'fas fa-rss-square' },
{ icon: 'fas fa-ruble-sign' },
{ icon: 'fas fa-rupee-sign' },
{ icon: 'fab fa-safari' },
{ icon: 'fab fa-sass' },
{ icon: 'fas fa-save' }, { icon: 'far fa-save' },
{ icon: 'fab fa-schlix' },
{ icon: 'fab fa-scribd' },
{ icon: 'fas fa-search' },
{ icon: 'fas fa-search-minus' },
{ icon: 'fas fa-search-plus' },
{ icon: 'fab fa-searchengin' },
{ icon: 'fab fa-sellcast' },
{ icon: 'fab fa-sellsy' },
{ icon: 'fas fa-server' },
{ icon: 'fab fa-servicestack' },
{ icon: 'fas fa-share' },
{ icon: 'fas fa-share-alt' },
{ icon: 'fas fa-share-alt-square' },
{ icon: 'fas fa-share-square' }, { icon: 'far fa-share-square' },
{ icon: 'fas fa-shekel-sign' },
{ icon: 'fas fa-shield-alt' },
{ icon: 'fas fa-ship' },
{ icon: 'fab fa-shirtsinbulk' },
{ icon: 'fas fa-shopping-bag' },
{ icon: 'fas fa-shopping-basket' },
{ icon: 'fas fa-shopping-cart' },
{ icon: 'fas fa-shower' },
{ icon: 'fas fa-sign-in-alt' },
{ icon: 'fas fa-sign-language' },
{ icon: 'fas fa-sign-out-alt' },
{ icon: 'fas fa-signal' },
{ icon: 'fab fa-simplybuilt' },
{ icon: 'fab fa-sistrix' },
{ icon: 'fas fa-sitemap' },
{ icon: 'fab fa-skyatlas' },
{ icon: 'fab fa-skype' },
{ icon: 'fab fa-slack' },
{ icon: 'fab fa-slack-hash' },
{ icon: 'fas fa-sliders-h' },
{ icon: 'fab fa-slideshare' },
{ icon: 'fas fa-smile' }, { icon: 'far fa-smile' },
{ icon: 'fab fa-snapchat' },
{ icon: 'fab fa-snapchat-ghost' },
{ icon: 'fab fa-snapchat-square' },
{ icon: 'fas fa-snowflake' }, { icon: 'far fa-snowflake' },
{ icon: 'fas fa-sort' },
{ icon: 'fas fa-sort-alpha-down' },
{ icon: 'fas fa-sort-alpha-up' },
{ icon: 'fas fa-sort-amount-down' },
{ icon: 'fas fa-sort-amount-up' },
{ icon: 'fas fa-sort-down' },
{ icon: 'fas fa-sort-numeric-down' },
{ icon: 'fas fa-sort-numeric-up' },
{ icon: 'fas fa-sort-up' },
{ icon: 'fab fa-soundcloud' },
{ icon: 'fas fa-space-shuttle' },
{ icon: 'fab fa-speakap' },
{ icon: 'fas fa-spinner' },
{ icon: 'fab fa-spotify' },
{ icon: 'fas fa-square' }, { icon: 'far fa-square' },
{ icon: 'fab fa-stack-exchange' },
{ icon: 'fab fa-stack-overflow' },
{ icon: 'fas fa-star' }, { icon: 'far fa-star' },
{ icon: 'fas fa-star-half' }, { icon: 'far fa-star-half' },
{ icon: 'fab fa-staylinked' },
{ icon: 'fab fa-steam' },
{ icon: 'fab fa-steam-square' },
{ icon: 'fab fa-steam-symbol' },
{ icon: 'fas fa-step-backward' },
{ icon: 'fas fa-step-forward' },
{ icon: 'fas fa-stethoscope' },
{ icon: 'fab fa-sticker-mule' },
{ icon: 'fas fa-sticky-note' }, { icon: 'far fa-sticky-note' },
{ icon: 'fas fa-stop' },
{ icon: 'fas fa-stop-circle' }, { icon: 'far fa-stop-circle' },
{ icon: 'fab fa-strava' },
{ icon: 'fas fa-street-view' },
{ icon: 'fas fa-strikethrough' },
{ icon: 'fab fa-stripe' },
{ icon: 'fab fa-stripe-s' },
{ icon: 'fab fa-studiovinari' },
{ icon: 'fab fa-stumbleupon' },
{ icon: 'fab fa-stumbleupon-circle' },
{ icon: 'fas fa-subscript' },
{ icon: 'fas fa-subway' },
{ icon: 'fas fa-suitcase' },
{ icon: 'fas fa-sun' }, { icon: 'far fa-sun' },
{ icon: 'fab fa-superpowers' },
{ icon: 'fas fa-superscript' },
{ icon: 'fab fa-supple' },
{ icon: 'fas fa-sync' },
{ icon: 'fas fa-sync-alt' },
{ icon: 'fas fa-table' },
{ icon: 'fas fa-tablet' },
{ icon: 'fas fa-tablet-alt' },
{ icon: 'fas fa-tachometer-alt' },
{ icon: 'fas fa-tag' },
{ icon: 'fas fa-tags' },
{ icon: 'fas fa-tasks' },
{ icon: 'fas fa-taxi' },
{ icon: 'fab fa-telegram' },
{ icon: 'fab fa-telegram-plane' },
{ icon: 'fab fa-tencent-weibo' },
{ icon: 'fas fa-terminal' },
{ icon: 'fas fa-text-height' },
{ icon: 'fas fa-text-width' },
{ icon: 'fas fa-th' },
{ icon: 'fas fa-th-large' },
{ icon: 'fas fa-th-list' },
{ icon: 'fab fa-themeisle' },
{ icon: 'fas fa-thermometer-empty' },
{ icon: 'fas fa-thermometer-full' },
{ icon: 'fas fa-thermometer-half' },
{ icon: 'fas fa-thermometer-quarter' },
{ icon: 'fas fa-thermometer-three-quarters' },
{ icon: 'fas fa-thumbs-down' }, { icon: 'far fa-thumbs-down' },
{ icon: 'fas fa-thumbs-up' }, { icon: 'far fa-thumbs-up' },
{ icon: 'fas fa-thumbtack' },
{ icon: 'fas fa-ticket-alt' },
{ icon: 'fas fa-times' },
{ icon: 'fas fa-times-circle' }, { icon: 'far fa-times-circle' },
{ icon: 'fas fa-tint' },
{ icon: 'fas fa-toggle-off' },
{ icon: 'fas fa-toggle-on' },
{ icon: 'fas fa-trademark' },
{ icon: 'fas fa-train' },
{ icon: 'fas fa-transgender' },
{ icon: 'fas fa-transgender-alt' },
{ icon: 'fas fa-trash' },
{ icon: 'fas fa-trash-alt' }, { icon: 'far fa-trash-alt' },
{ icon: 'fas fa-tree' },
{ icon: 'fab fa-trello' },
{ icon: 'fab fa-tripadvisor' },
{ icon: 'fas fa-trophy' },
{ icon: 'fas fa-truck' },
{ icon: 'fas fa-tty' },
{ icon: 'fab fa-tumblr' },
{ icon: 'fab fa-tumblr-square' },
{ icon: 'fas fa-tv' },
{ icon: 'fab fa-twitch' },
{ icon: 'fab fa-twitter' },
{ icon: 'fab fa-twitter-square' },
{ icon: 'fab fa-typo3' },
{ icon: 'fab fa-uber' },
{ icon: 'fab fa-uikit' },
{ icon: 'fas fa-umbrella' },
{ icon: 'fas fa-underline' },
{ icon: 'fas fa-undo' },
{ icon: 'fas fa-undo-alt' },
{ icon: 'fab fa-uniregistry' },
{ icon: 'fas fa-universal-access' },
{ icon: 'fas fa-university' },
{ icon: 'fas fa-unlink' },
{ icon: 'fas fa-unlock' },
{ icon: 'fas fa-unlock-alt' },
{ icon: 'fab fa-untappd' },
{ icon: 'fas fa-upload' },
{ icon: 'fab fa-usb' },
{ icon: 'fas fa-user' }, { icon: 'far fa-user' },
{ icon: 'fas fa-user-circle' }, { icon: 'far fa-user-circle' },
{ icon: 'fas fa-user-md' },
{ icon: 'fas fa-user-plus' },
{ icon: 'fas fa-user-secret' },
{ icon: 'fas fa-user-times' },
{ icon: 'fas fa-users' },
{ icon: 'fab fa-ussunnah' },
{ icon: 'fas fa-utensil-spoon' },
{ icon: 'fas fa-utensils' },
{ icon: 'fab fa-vaadin' },
{ icon: 'fas fa-venus' },
{ icon: 'fas fa-venus-double' },
{ icon: 'fas fa-venus-mars' },
{ icon: 'fab fa-viacoin' },
{ icon: 'fab fa-viadeo' },
{ icon: 'fab fa-viadeo-square' },
{ icon: 'fab fa-viber' },
{ icon: 'fas fa-video' },
{ icon: 'fab fa-vimeo' },
{ icon: 'fab fa-vimeo-square' },
{ icon: 'fab fa-vimeo-v' },
{ icon: 'fab fa-vine' },
{ icon: 'fab fa-vk' },
{ icon: 'fab fa-vnv' },
{ icon: 'fas fa-volume-down' },
{ icon: 'fas fa-volume-off' },
{ icon: 'fas fa-volume-up' },
{ icon: 'fab fa-vuejs' },
{ icon: 'fab fa-weibo' },
{ icon: 'fab fa-weixin' },
{ icon: 'fab fa-whatsapp' },
{ icon: 'fab fa-whatsapp-square' },
{ icon: 'fas fa-wheelchair' },
{ icon: 'fab fa-whmcs' },
{ icon: 'fas fa-wifi' },
{ icon: 'fab fa-wikipedia-w' },
{ icon: 'fas fa-window-close' }, { icon: 'far fa-window-close' },
{ icon: 'fas fa-window-maximize' }, { icon: 'far fa-window-maximize' },
{ icon: 'fas fa-window-minimize' },
{ icon: 'fas fa-window-restore' }, { icon: 'far fa-window-restore' },
{ icon: 'fab fa-windows' },
{ icon: 'fas fa-won-sign' },
{ icon: 'fab fa-wordpress' },
{ icon: 'fab fa-wordpress-simple' },
{ icon: 'fab fa-wpbeginner' },
{ icon: 'fab fa-wpexplorer' },
{ icon: 'fab fa-wpforms' },
{ icon: 'fas fa-wrench' },
{ icon: 'fab fa-xbox' },
{ icon: 'fab fa-xing' },
{ icon: 'fab fa-xing-square' },
{ icon: 'fab fa-y-combinator' },
{ icon: 'fab fa-yahoo' },
{ icon: 'fab fa-yandex' },
{ icon: 'fab fa-yandex-international' },
{ icon: 'fab fa-yelp' },
{ icon: 'fas fa-yen-sign' },
{ icon: 'fab fa-yoast' },
{ icon: 'fab fa-youtube'}
];
var itemTemplate = $('.icon-picker-list').clone(true).html();

$('.icon-picker-list').html('');

// Loop through JSON and appends content to show icons
$(icons).each(function(index) {
	var itemtemp = itemTemplate;
	var item = icons[index].icon;

	if (index == selectedIcon) {
		var activeState = 'active'
	} else {
		var activeState = ''
	}

	itemtemp = itemtemp.replace(/{{item}}/g, item).replace(/{{index}}/g, index).replace(/{{activeState}}/g, activeState);

	$('.icon-picker-list').append(itemtemp);
});

// Variable that's passed around for active states of icons
var selectedIcon = null;

$('.icon-class-input').each(function() {
	if ($(this).val() != null) {
		$(this).siblings('.selected-icon').addClass($(this).val());
	}
});

// To be set to which input needs updating
var iconInput = null;

// Click function to set which input is being used
$('.picker-button').click(function() {
	// Sets var to which input is being updated
	iconInput = $(this).siblings('.icon-class-input');
	// Shows Bootstrap Modal
	$('#iconPicker').modal('show');
	// Sets active state by looping through the list with the previous class from the picker input
	selectedIcon = findInObject(icons, 'icon', $(this).siblings('.icon-class-input').val());
	// Removes any previous active class
	$('.icon-picker-list a').removeClass('active');
	// Sets active class
	$('.icon-picker-list a').eq(selectedIcon).addClass('active');
});

// Click function to select icon
$(document).on('click', '.icon-picker-list a', function() {
	// Sets selected icon
	selectedIcon = $(this).data('index');

	// Removes any previous active class
	$('.icon-picker-list a').removeClass('active');
	// Sets active class
	$('.icon-picker-list a').eq(selectedIcon).addClass('active');
});

// Update icon input
$('#change-icon').click(function() {
	iconInput.val(icons[selectedIcon].icon);
	iconInput.siblings('.selected-icon').attr('class', 'selected-icon');
	iconInput.siblings('.selected-icon').addClass(icons[selectedIcon].icon);
	$('#iconPicker').modal('hide');
	console.log(iconInput);
	console.log(icons[selectedIcon].icon);
});

function findInObject(object, property, value) {
	for (var i = 0; i < object.length; i += 1) {
		if (object[i][property] === value) {
			return i;
		}
	}
}