name: "Build & push docker image on release"

on:
  release:
    types:
      - published

jobs:
  docker-build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v2

      - name: "Calculate Docker image tag from release"
        if: github.repository == 'mviewer/mviewerstudio'
        id: version
        run: |
          DOCKER_TAG=$(echo "${{ github.ref }}" | cut -d'/' -f3)
          echo "::set-output name=VERSION::$DOCKER_TAG"

      - name: "Build the Docker containers"
        if: github.repository == 'mviewer/mviewerstudio'
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker compose build

      - name: "Log in to Docker Hub"
        if: github.repository == 'mviewer/mviewerstudio'
        uses: azure/docker-login@v1
        with:
          username: '${{ secrets.DOCKER_HUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_PASSWORD }}'

      - name: "Tag and push Docker image"
        if: github.repository == 'mviewer/mviewerstudio'
        run: |
          docker tag mviewer/mviewerstudio:latest mviewer/mviewerstudio:${{ steps.version.outputs.VERSION }}
          docker push mviewer/mviewerstudio:${{ steps.version.outputs.VERSION }}
